### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by TrySound** [jonathantneal/closest#10]
@jonathantneal Publish closest on npm, please. I prepared package.json. And add me to collaborators.

**Comment by TrySound** [comment]
Give me access to npm, please. Need to fix release order.

**Comment by TrySound** [comment]
@jonathantneal

**Comment by jonathantneal** [comment]
I had made you a collaborator on GitHub. I’ll look into how I would get you access to npm.

**Comment by TrySound** [comment]
You published on npm with your changes, which was after github release, but with the same version.
At the right of npm repo "Collaborators" -> "+"
