### ISSUE TITLE
Not working anymore in IE11

### ISSUE THREAD

**Issue by herrernst** [jonathantneal/closest#13]
Your new version 2.0 is not working anymore at least in IE 11. Just try the test suite:
https://rawgit.com/jonathantneal/closest/a92c9675e82d5d0186ced05e29a363677ec61a91/test/index.html
Error happens when not finding an matching element, `matches` is called on `document`, which doesn't have this method. I think your check for the document node is wrong, you check against `nodeType !== 11` in https://github.com/jonathantneal/closest/blob/master/closest.js#L21, but the `nodeType` of `document` is 9, see https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType.

**Comment by herrernst** [comment]
I think it would be better to check if the `nodeType` _is_ that of an `Element` (`1`), because the specifcation states "[Let elements be context object’s inclusive ancestors that are elements](https://dom.spec.whatwg.org/#dom-element-closest)".

**Comment by jonathantneal** [comment]
@herrernst, thanks for bringing this to my attention. Would you check pull request #14 to see if this resolves your issue? I will pull and release ASAP.

**Comment by herrernst** [comment]
Thanks, but can only check Monday earliest.

**Comment by jonathantneal** [comment]
I’ll make a test in CodePen and use cross browser testing to confirm.

**Comment by jonathantneal** [comment]
This has been fixed and the update published. Thank you so much @herrernst for reporting this so quickly!

**Comment by herrernst** [comment]
Can confirm it works now, thank you!
