### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by zaruda** [jonathantneal/closest#23]
window is not defined while server-side rendered

**Comment by willtonkin** [comment]
surely you need a DOM in order to use this polyfill? I'd suggest you don't apply DOM polyfills when rendering server-side

**Comment by willtonkin** [comment]
ah, I can see that being annoying. The question then is which project is responsable for being SSR friendly in a chain like that. I'd agree then, this could easily be made to be. I guess it's a question then for the maintainer :)

**Comment by jonathantneal** [comment]
I will do my best to fix this today.

**Comment by zaruda** [comment]
Hi @jonathantneal !
You can check this updates which were made by coreui team today. https://github.com/coreui/coreui-react/pull/53

**Comment by jonathantneal** [comment]
Sorry to have missed their cut off, @zaruda. I’ll still try to resolve this today.
