### ISSUE TITLE
3.0.0 version seems to be broken. JS not present

### ISSUE THREAD

**Issue by jaichandra** [jonathantneal/closest#25]

**Comment by Jetski5822** [comment]
Same :( - reverted to 2.0.2

**Comment by Biohazord** [comment]
I ran into the same issue. We only use this in the browser so it was a quick fix. I changed my require syntax to be just `require("element-closest/browser");`

**Comment by jonathantneal** [comment]
I’ll be back from vacation next week and will publish a patch release with the missing files.

**Comment by jonathantneal** [comment]
@Biohazord provided the solution that was probably the real issue.

The issue was not that there were missing files, as evidenced by https://unpkg.com/element-closest@3.0.0/

**Comment by cekvenich** [comment]
Is there a version for jsdeliver?

I don't want to add an unstable dependency as unpackaged is not stable.
