### ISSUE TITLE
"Use of const in strict mode" in pre-es6 browsers

### ISSUE THREAD

**Issue by vitalyster** [jonathantneal/closest#27]
Please not use `const`, or please provide es5 version for npm, or stop declare android 2.2+ support :)

**Comment by jonathantneal** [comment]
Hi @vitalyster, you’ll want to import or require the `browser.js` version.

```js
import 'element-closest/browser';
```

```js
require('element-closest/browser');
```

Alternatively, you can reference the browser version directly from npm.

```html
<script src="https://unpkg.com/element-closest/browser"></script>
```

The `browser.js` version is for browsers. The `index.js` version is for Node. The `index.mjs` is for Node with experimental modules enabled.

**Comment by seyfer** [comment]
@jonathantneal please add this information to docs. I was confused too.
