### ISSUE TITLE
Missing tag

### ISSUE THREAD

**Issue by mislav** [jonathantneal/closest#4]
We can't use the bower "0.0.1" version right now because you haven't tagged a release.

I propose:

1. Tag "0.0.1" on master right now, because that is what `bower.json` references
2. Then, remove `closest.legacy.js`(because as README indicates, very few people would actually make use of it), bump the bower version to "1.0.0", and tag that as well. People who need the legacy stuff can ride the "0.0.1".

Thanks

**Comment by jonathantneal** [comment]
@mislav I’ve pushed some changes and let me know if this resolves the issue

**Comment by mislav** [comment]
That's really helpful; thank you Jonathan.
