### ISSUE TITLE
"ms" prefix not detected on IE9

### ISSUE THREAD

**Issue by mislav** [jonathantneal/closest#5]
`getComputedStyle(document.documentElement).cssText.match(/-(moz|webkit|ms)-/)` doesn't return a match on IE9 (in VM provided by ModernIE), and thus "ms" prefix is not detected and `matches` doesn't work.

`cssText` is completely blank on documentElement. What is it supposed to contain? Isn't it better to detect a prefix by iterating through a list of known prefixes and detecting whether `#{prefix}MatchesSelector` exists on Element.protoype?

**Comment by jonathantneal** [comment]
Great catch. Corrected, tested, and committed! Would you confirm?

**Comment by mislav** [comment]
It'll be a day before I can confirm, but if you tested this out then please go ahead and tag a release.

I would only wish that the detection code is simpler, i.e. per my suggestion above.

**Comment by TrySound** [comment]
@jonathantneal Another way to detect now. Close this, please.
Or give me access :)
